### ISSUE TITLE
Bulletlist and Numberlist not working

### ISSUE THREAD

**Issue by Niby94** [mstahv/tinymcewrapper#9]
There seems to an issue with the number list and bullet lists, as they are not shown, no matter what configuration I try.

This is my current configuration:
`tinyMCETextField.setConfig("{ menubar: false,"
				+ "plugins: [ 'lists advlist' ],"
				+ "toolbar: 'undo redo | styleselect | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent'}");`

Even with the default configuration (so by **not** calling `setConfig()`), the lists will not show.

**Comment by mstahv** [comment]
4.1 is now out with a tinymce version fixed to a version without the regression
